# Generated by Django 2.2.5 on 2019-10-04 08:54

import Payments.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='payment_receipt',
            field=models.ImageField(blank=True, upload_to=Payments.models.upload_to, verbose_name='Ödeme dekontu:'),
        ),
    ]
