# Generated by Django 2.2.5 on 2019-10-16 07:54

import Payments.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Payments', '0004_remove_payment_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='image',
            field=models.ImageField(upload_to=Payments.models.upload_to, verbose_name='Ödeme dekontu:'),
        ),
    ]
