# Generated by Django 2.2.5 on 2019-10-02 08:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import users.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=10, null=True, verbose_name='Telefon numarası')),
                ('title', models.CharField(choices=[(None, 'Seçiniz'), ('1', 'Ege Üniversitesi öğrencisi / personeli / mezunu.'), ('2', 'Gazi / engelli / şehit yakını.'), ('3', 'Kurum dışı')], max_length=50, null=True, verbose_name='Kurum bağlantısı')),
                ('image', models.ImageField(upload_to=users.models.upload_to, verbose_name='Media:')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı')),
            ],
            options={
                'verbose_name_plural': 'Profiller',
            },
        ),
    ]
