# Generated by Django 2.2.5 on 2019-10-04 05:33

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20191003_1442'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, upload_to=users.models.upload_to, verbose_name='Media:'),
        ),
    ]
