# Generated by Django 2.2.5 on 2019-10-04 08:54

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20191004_0834'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='national_id',
            field=models.IntegerField(null=True, verbose_name='Tc kimlik'),
        ),
        migrations.AddField(
            model_name='profile',
            name='other_phone',
            field=models.CharField(max_length=10, null=True, verbose_name='Diğer telefon numarası'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, upload_to=users.models.upload_to, verbose_name='Belge:'),
        ),
    ]
