# Generated by Django 2.2.5 on 2019-10-04 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20191004_1154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='national_id',
            field=models.CharField(max_length=11, null=True, verbose_name='T.C Kimlik'),
        ),
    ]
