# Generated by Django 2.2.5 on 2019-10-07 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20191004_1159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='national_id',
            field=models.CharField(max_length=12, null=True, verbose_name='T.C Kimlik'),
        ),
    ]
