# Generated by Django 2.2.5 on 2019-10-09 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20191007_1013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='nationalid',
            field=models.CharField(max_length=11, null=True, verbose_name='T.C Kimlik'),
        ),
    ]
