# Generated by Django 2.2.5 on 2019-10-15 13:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0010_auto_20191009_1135'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataHolder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_upload_date', models.DateTimeField(max_length=100, null=True, verbose_name='Belge yükleme tarihi:')),
                ('profile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.Profile', verbose_name='Yükleyen kullanıcı:')),
            ],
        ),
    ]
