# Generated by Django 2.2.5 on 2019-10-15 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20191009_1135'),
        ('DateHolder', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DataHolder',
            new_name='DateHolder',
        ),
    ]
