# Generated by Django 2.2.5 on 2019-10-16 06:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('DateHolder', '0002_auto_20191015_1605'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dateholder',
            name='profile',
        ),
        migrations.AddField(
            model_name='dateholder',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Yükleyen kullanıcı:'),
        ),
    ]
