# Generated by Django 2.2.5 on 2019-10-16 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DateHolder', '0003_auto_20191016_0939'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dateholder',
            options={'verbose_name_plural': 'Belge Yüklenme Tarihleri'},
        ),
    ]
