# Generated by Django 2.2.5 on 2019-10-06 11:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0007_auto_20191005_1510'),
        ('Payments', '0003_auto_20191005_1728'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('prereg', '0002_remove_preregistration_course'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinalRegistration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.Course')),
                ('payment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Payments.Payment')),
                ('prereg', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='prereg.PreRegistration')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
