# Generated by Django 2.2.5 on 2019-10-07 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finalreg', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='finalregistration',
            options={'verbose_name_plural': 'Kesin Kayıtlar'},
        ),
        migrations.RemoveField(
            model_name='finalregistration',
            name='prereg',
        ),
    ]
