# Generated by Django 2.2.5 on 2019-10-10 10:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('finalreg', '0002_auto_20191007_2042'),
    ]

    operations = [
        migrations.AddField(
            model_name='finalregistration',
            name='registering_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
