# Generated by Django 2.2.5 on 2019-10-04 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CourseRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_title', models.CharField(max_length=250, null=True)),
                ('request_content', models.TextField(max_length=1000, null=True)),
            ],
        ),
    ]
