# Generated by Django 2.2.5 on 2019-10-05 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_requests', '0002_courserequest_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='courserequest',
            name='limit_max',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='courserequest',
            name='limit_min',
            field=models.IntegerField(null=True),
        ),
    ]
