# Generated by Django 2.2.5 on 2019-10-07 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course_requests', '0003_auto_20191005_1506'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='courserequest',
            options={'verbose_name_plural': 'Kurs Talepleri'},
        ),
    ]
