# Generated by Django 2.2.5 on 2019-10-15 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_requests', '0005_auto_20191009_1350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursegiven',
            name='request_content',
            field=models.TextField(max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='coursetaken',
            name='request_content',
            field=models.TextField(max_length=2000, null=True),
        ),
    ]
