# Generated by Django 2.2.5 on 2019-10-03 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, null=True, verbose_name='Kurs:')),
                ('start_at', models.DateTimeField(null=True, verbose_name='Başlangıç tarihi:')),
                ('finish_at', models.DateTimeField(null=True, verbose_name='Bitiş tarihi:')),
                ('content', models.TextField(blank=True, max_length=1500, null=True, verbose_name='İçerik:')),
                ('limit', models.IntegerField(null=True, verbose_name='Kontenjan:')),
                ('status', models.CharField(choices=[(None, 'Seçiniz'), ('1', 'Devam ediyor.'), ('2', 'Yeni açıldı, kayıtlar devam ediyor.'), ('3', 'Bitti.')], max_length=45, null=True, verbose_name='Kurs Durumu:')),
                ('course_code', models.CharField(blank=True, editable=False, max_length=5, null=True)),
            ],
        ),
    ]
