# Generated by Django 2.2.5 on 2019-10-03 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='price',
            field=models.IntegerField(null=True, verbose_name='Fiyat:'),
        ),
    ]
