# Generated by Django 2.2.5 on 2019-10-04 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_auto_20191003_1605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='status',
            field=models.CharField(choices=[(None, 'Seçiniz'), ('1', 'Devam ediyor.'), ('2', 'Kayıtlar açıldı.'), ('3', 'Bitti.')], max_length=45, null=True, verbose_name='Kurs Durumu:'),
        ),
    ]
