# Generated by Django 2.2.5 on 2019-10-04 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prereg', '0002_remove_preregistration_course'),
        ('courses', '0005_course_prereg'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='prereg',
        ),
        migrations.AddField(
            model_name='course',
            name='prereg',
            field=models.ManyToManyField(null=True, to='prereg.PreRegistration', verbose_name='Ön başvuru:'),
        ),
    ]
