# Generated by Django 2.2.5 on 2019-10-05 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_auto_20191004_1426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='prereg',
            field=models.ManyToManyField(to='prereg.PreRegistration', verbose_name='Ön başvuru:'),
        ),
    ]
