# Generated by Django 2.2.5 on 2019-10-06 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_auto_20191005_1510'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='registering_extension',
            field=models.CharField(editable=False, max_length=25, null=True),
        ),
    ]
