# Generated by Django 2.2.5 on 2019-10-06 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_course_registering_extension'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='is_registerable',
            field=models.BooleanField(default=False, verbose_name='Kesin kayda açık mı?:'),
        ),
        migrations.AlterField(
            model_name='course',
            name='registering_extension',
            field=models.CharField(max_length=25, null=True),
        ),
    ]
