# Generated by Django 2.2.5 on 2019-10-07 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_auto_20191006_1741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='is_registerable',
            field=models.BooleanField(default=False, verbose_name='Kesin kaydı aç.'),
        ),
        migrations.AlterField(
            model_name='course',
            name='prereg',
            field=models.ManyToManyField(blank=True, to='prereg.PreRegistration', verbose_name='Ön başvuru:'),
        ),
        migrations.AlterField(
            model_name='course',
            name='registering_extension',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='status',
            field=models.CharField(choices=[(None, 'Seçiniz'), ('1', 'Devam ediyor.'), ('2', 'Ön kayıtlar açıldı.'), ('3', 'Kesin kayıtlar açık.'), ('4', 'Bitti.')], max_length=45, null=True, verbose_name='Kurs Durumu:'),
        ),
    ]
