# Generated by Django 2.2.5 on 2019-10-07 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_auto_20191007_0959'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'verbose_name_plural': 'Kurslar'},
        ),
    ]
