# Generated by Django 2.2.5 on 2019-10-11 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0011_auto_20191007_2042'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseDiscount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount_1', models.IntegerField(null=True, verbose_name='Ege Üniversitesi personel / öğrenci / mezun indirimi:')),
                ('discount_2', models.IntegerField(null=True, verbose_name='Gazi / engell / şehit yakını indirimi:')),
                ('bank_info', models.TextField(max_length=500, null=True, verbose_name='Banka hesap bilgileri:')),
            ],
            options={
                'verbose_name_plural': 'İndirim',
            },
        ),
        migrations.AlterField(
            model_name='course',
            name='content',
            field=models.TextField(blank=True, max_length=6000, null=True, verbose_name='İçerik:'),
        ),
    ]
