# Generated by Django 2.2.5 on 2019-10-11 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0013_auto_20191011_1417'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='category',
            field=models.CharField(choices=[(None, 'Seçiniz'), ('1', 'Programlama, Yazılım'), ('2', 'Dil'), ('3', 'Sanat'), ('4', 'Kişisel Gelişim')], max_length=45, null=True, verbose_name='Kurs Kategori:'),
        ),
    ]
