# Generated by Django 2.2.5 on 2019-10-11 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0014_course_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='category',
            field=models.CharField(choices=[(None, 'Seçiniz'), ('1', 'Programlama, Yazılım'), ('2', 'Dil'), ('3', 'Sanat'), ('4', 'Kişisel Gelişim'), ('5', 'Sağlık'), ('6', 'Siber Güvenlik'), ('7', 'Edebiyat'), ('8', 'Tarih'), ('9', 'Eğitim'), ('10', 'Ekonomi'), ('11', 'Bilim, Temel Bilimler'), ('12', 'Psikoloji')], max_length=45, null=True, verbose_name='Kurs Kategori:'),
        ),
    ]
