# Generated by Django 2.2.5 on 2019-10-11 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0015_auto_20191011_1441'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='limit',
        ),
        migrations.AlterField(
            model_name='course',
            name='category',
            field=models.CharField(choices=[(None, 'Seçiniz'), ('1', 'Programlama, Yazılım'), ('2', 'Dil'), ('3', 'Sanat'), ('4', 'Mühendislik'), ('5', 'Sağlık'), ('6', 'Siber Güvenlik'), ('7', 'Eğitim'), ('8', 'Sosyal Bilimler'), ('9', 'Temel Bilimler'), ('10', 'Psikoloji')], max_length=45, null=True, verbose_name='Kurs Kategori:'),
        ),
    ]
