# Generated by Django 2.2.5 on 2019-10-04 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prereg', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='preregistration',
            name='course',
        ),
    ]
