# Generated by Django 2.2.5 on 2019-10-07 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prereg', '0002_remove_preregistration_course'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='preregistration',
            options={'verbose_name_plural': 'Ön Başvurular'},
        ),
    ]
